import Head from 'next/head';
import App from './_app';

export default function Home() {
  return (
    <>
      <Head>
        <title>Real Estate </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className>
        <div>
          <App />
        </div>
      </main>
    </>
  );
}
